### ISSUE TITLE
Incorrect and missed splits for some datasets

### ISSUE THREAD

**Issue by teasgen** [LAION-AI/CLIP_benchmark#104]
I'm trying to use OxfordIIITPet dataset, and as indicated in [Pets](https://pytorch.org/vision/main/generated/torchvision.datasets.OxfordIIITPet.html) it has splits "trainval", "test".
In your code are available only "train" and "test" splits. When I run the code it fails with error: 
ValueError: Unknown value 'train' for argument split. Valid values are {'trainval', 'test'}.
Please, fix it.

The second question is how to use the validation splits with your code?  For instance, [DTD](https://pytorch.org/vision/main/generated/torchvision.datasets.DTD.html) has "train", "val", "test" parts, and I think it will be great, if you add possibility to use it. I need it to perform linear evaluation with train and validation parts.

**Comment by mehdidc** [comment]
Hi @teasgen thanks for reporting the errors, will go over the datasets and  fix this

**Comment by mehdidc** [comment]
fixed, please retry

**Comment by teasgen** [comment]
> fixed, please retry

Thank you, it works. When this package will be updated in https://pypi.org/project/clip-benchmark? I think the 1.4.0 version is  outdated and package hasn't been updated for 6 month.

**Comment by mehdidc** [comment]
@teasgen indeed would make sense to update it now. @rom1504 could you please let me know how you did that previously, from what I understand it  was through github actions? or if you have time please just do it. btw HISTORY.rst is already updated with the  (1.5.0)  changes.

**Comment by rom1504** [comment]
You need a commit named "Release 1.5.0" and you need to update history file
and the version in setup.py

**Comment by mehdidc** [comment]
Alright will do, thanks @rom1504

**Comment by mehdidc** [comment]
Ok 1.5.0 is available now, closing.
