### ISSUE TITLE
Benchmark siglip 

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/CLIP_benchmark#108]
https://twitter.com/giffmana/status/1707327094982672666?t=5L0oyEbDB1wrHfV0yZSSyA&s=19

**Comment by marcusinthesky** [comment]
I'm excited to see these results. I noticed that while authors claim amazing results:
![Screenshot from 2023-10-05 10-19-50](https://github.com/LAION-AI/CLIP_benchmark/assets/26429489/86941183-42ca-4e65-9e38-a4b2a31b961f)
OpenCLIP and OpenAI B16 224 models are typically 512 hidden dimensions, not 768 like in SigLIP:
![Screenshot from 2023-10-05 10-17-02](https://github.com/LAION-AI/CLIP_benchmark/assets/26429489/c95b2716-8303-4c30-a276-8ba865bf7171)
This suggests to me that the base models far more comparable to OpenCLIP and OpenAI L14 models, which would place them closer to EVA-CLIP results, but with fewer hidden layers, as hidden and projection sizes have a significant impact on recall performance.

**Comment by mehdidc** [comment]
@rom1504 @marcusinthesky Here is a notebook with ImageNet zero-shot classification evals: https://colab.research.google.com/drive/1IadaMQk4m7DQSkUuCCsviRHomnFRqGSr?usp=sharing, based on SigCLIP  notebook.

For ViT-B/16 224 res (196 patches), I don't fin the same results as in Table 3 (https://arxiv.org/pdf/2303.15343.pdf), I obtain 74.4 whereas it is reported 76.2 in the paper, not sure what I am missing. @xiaohuazhai @lucasb-eyer do you do anything specific on zero-shot evaluation that is not in the SigCLIP notebook, e.g. different pre-preprocessing ? for classnames/templates I am using openai ones, I suppose it was the same there?

**Comment by mehdidc** [comment]
Also, above is simply wrapping the Jax model. Once I reproduce the results, I can integrate it directly to clip benchmark, although ideallyI think we should support SigCLIP models directly in openclip with PyTorch, @rwightman do you think it's doable ? I guess it would similar to what you did in `timm` with other `big_vision` models.

**Comment by rwightman** [comment]
@mehdidc I've got SigLIP weights working in OpenCLIP, BUT, the merge with CLIPA a and cleaning up the combo of pooling options, and tokenizer configs is a bit of a mess... so taking much longer than I'd hoped (SigLIP itself was verified over a week ago now).

**Comment by mehdidc** [comment]
Closing as now SigLIP models are supported in OpenCLIP
