### ISSUE TITLE
Overwritten zeroshot templates for webdataset eval

### ISSUE THREAD

**Issue by djghosh13** [LAION-AI/CLIP_benchmark#109]
#98 added better support for custom zeroshot prompt templates. However, the exact implementation results in behavior which conflicts with webdataset datasets (e.g. "wds/cifar10") stored on Huggingface or locally. Specifically:
1. For zeroshot classification, templates are loaded from `en_zeroshot_classification_templates.json`
2. If the dataset name is not recognized, the templates are set to IN1k templates
3. `build_wds_dataset` loads classnames and templates from the source (local filesystem or Huggingface repo) ([line 731](https://github.com/LAION-AI/CLIP_benchmark/blob/567f01c655514f5f3caaea55d73d2c946f6bc1a1/clip_benchmark/datasets/builder.py#L731))
4. `ds.templates = templates` overwrites the templates on [line 45](https://github.com/LAION-AI/CLIP_benchmark/blob/567f01c655514f5f3caaea55d73d2c946f6bc1a1/clip_benchmark/datasets/builder.py#L454)

This affects all wds datasets, though it probably hasn't changed results in the majority of cases, where the dataset name and templates match the defaults in `en_zeroshot_classification_templates.json`.

A fix should probably either:
* Never overwrite `ds.templates` if it already exists; or
* Overwrite `ds.templates` only if the `custom_template_file` parameter is set (i.e. custom template takes precedence over webdataset template)

**Comment by mehdidc** [comment]
Thanks a lot @djghosh13 ! I haven't noticed this, I think it would make sense to overwrite only if custom is provided (second option).

**Comment by mehdidc** [comment]
Fixed.
