### ISSUE TITLE
WDS classnames and empty lines

### ISSUE THREAD

**Issue by mehdidc** [LAION-AI/CLIP_benchmark#111]
@djghosh13  when comparing the results of benchmark with local files vs WDS equivalent, I noticed that for `wds/vtab/clevr_closest_object_distance`,  reading the classnames from https://huggingface.co/datasets/clip-benchmark/wds_vtab-clevr_closest_object_distance/blob/main/classnames.txt will cause it to ignore the 4th line because there is a `if line.strip()` as a condition https://github.com/LAION-AI/CLIP_benchmark/blob/main/clip_benchmark/datasets/builder.py#L724, there it was actually meant to be empty, I was using classnames from LiT paper:

![lit](https://github.com/LAION-AI/CLIP_benchmark/assets/509507/22daedba-955f-46a6-8b87-35961eae3ea5)

Otherwise, everything else was fine.

**Comment by djghosh13** [comment]
Thanks for catching that! The `line.strip()` was an attempt to remove empty lines at the end of the file, not having realized that `.splitlines()` already factors in trailing newlines. That can be easily fixed to simply return the lines as is with no filtering.

**Comment by mehdidc** [comment]
Fixed.
