### ISSUE TITLE
JSON files are not included in install, leads to error

### ISSUE THREAD

**Issue by djghosh13** [LAION-AI/CLIP_benchmark#29]
Running `python setup.py install` fails to include JSON files (e.g. classnames and prompts), which leads to a FileNotFoundError for `en_classnames.json` in the `build_dataset` function.

I would suggest including *.json in the manifest file:
```
recursive-include * *.json
```

**Comment by djghosh13** [comment]
On a related note, loading VTAB (and I assume TFDS) datasets is broken right now because `classnames` is no longer a global variable, so it errors on lines like
```py
classes = classnames["caltech101_vtab"]
```

**Comment by rom1504** [comment]
fixed the manifest problem https://github.com/LAION-AI/CLIP_benchmark/blob/main/MANIFEST.in

**Comment by rom1504** [comment]
Fixed vtab too
