### ISSUE TITLE
support a generic clip-like model

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/CLIP_benchmark#30]
instead of supporting ton of models like suggested in https://github.com/LAION-AI/CLIP_benchmark/issues/1

let's let the user pass a model looking like clip

for example https://github.com/FreddeFrallan/Multilingual-CLIP is like this

**Comment by rom1504** [comment]
ways here:
* use https://github.com/dmarx/Multi-Modal-Comparators
* implement a few simple clip variants here (mclip, chinese clip, japanese clip)
* expose a way to plug any clip-looking function here (and use it in python ?) ?
* something similar than mmc but packaged

**Comment by rom1504** [comment]
mmc is not usable, see https://github.com/dmarx/Multi-Modal-Comparators/issues/41

so I'm thinking to take this plan
1. define a simple generic interface
2. implement a few interesting clips with optional deps
3. when happy with result, move to dedicated package

**Comment by dmarx** [comment]
I haven't touched MMC in a while and had recently been thinking about revisiting it. I think I have a solution that satisfies both my original goal and your packaging needs, but I'd also be open to starting with a fresh solution and use lessons learned. Anyway, here's the idea I had with mmc:

* trim the package down to a bare installation, maybe shipping with open-clip or clip-anytorch
* provide scripts and instructions users can use to install all models, groups of models, or individual models as needed. this could be as simple as renaming the current pyproject.toml so it isn't auto-detected by build tools and just add an additional build step to rename this file. 

Need to double check that it's ready for merge, but the changes staged in the ezmode PR adopts the openai/CLIP interface, including returning preprocessor and attaching tokenizer to `clip.tokenize`

**Comment by dmarx** [comment]
Another MMC-esque generic interface to consider: https://github.com/salesforce/LAVIS

**Comment by rom1504** [comment]
#50 is a first part in this

**Comment by rom1504** [comment]
mostly done
