### ISSUE TITLE
put all datasets in hugging face datasets

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/CLIP_benchmark#4]
wouldn't that be easier ?
the current download procedure is so cumbersome, crazy

**Comment by rom1504** [comment]
So my current best idea on this is to 
* Run all current data loader
* save the result in webdataset
* save that to huggingface
* add a generic huggingface data loader and offer that option for all supported dataset

Would make it possible to make this whole repo completely automated without having to do too much work on building automated downloader

**Comment by mehdidc** [comment]
I just added support for automatic download in the remaining datasets, but I think that would be great in any case, as some sources are slow to download from and some links might become dead or unusable (e.g. for onedrive, I had to find a way to direct download based on the original url, but it may not work in the future).

**Comment by rom1504** [comment]
awesome!

Yes I think it's good to have both

The slow method that gets things from the original source
and the fast method that is basically a cache of the slow method

Didn't have time to try this yet, but I'll get around to it. I think this method of using the existing data loader to produce standardized (and minimal) datasets should work well

**Comment by rom1504** [comment]
#52 is the same

**Comment by rom1504** [comment]
done
