### ISSUE TITLE
fix bug with paths

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/CLIP_benchmark#49]
for example 

/fsx/rom1504/CLIP_benchmark/clip_benchmark/datasets/vtab/svhn_classnames.json

trying to get the file from current dir instead of dataset dir 

@FreddeFrallan @djghosh13

**Comment by djghosh13** [comment]
What exactly do you mean? From what I can tell, the classnames JSON file is meant to be loaded from the folder that CLIP_benchmark was installed to (which is what is happening for me), and not from the dataset directory. Are you saying you'd prefer it read from the dataset directory?

**Comment by rom1504** [comment]
It used to be read from the dataset directory yes
Otherwise that means the files are all over the place no ?

Not sure when that changed, i guess a few commits back ?

**Comment by djghosh13** [comment]
Yeah, I guess so (I've only been using the library for the last few weeks). But I wouldn't say they're all over the place, it's just the classnames and zeroshot templates files stored in the CLIP_benchmark folder, and the data stored in the data folder, right?

Though this does differ from the webdataset setup we decided on where those are all stored together. I guess the importance of that distinction is whether people should easily be able to change the classnames/templates or not. So maybe we do want to move those back with the datasets.

**Comment by rom1504** [comment]
> it's just the classnames and zeroshot templates files stored in the CLIP_benchmark folder, and the data stored in the data folder, right?

I'm not talking about the classnames that are currently committed to the repo, but about the ones automatically downloaded by the tool. Those should be in dataset folder

**Comment by rom1504** [comment]
The ones in the repo are a different kind, kind of an override

**Comment by djghosh13** [comment]
I see, this is entirely different then.

**Comment by rom1504** [comment]
fixed
