### ISSUE TITLE
Add generative benchmarks on mscoco_captions

### ISSUE THREAD

**Issue by gpucce** [LAION-AI/CLIP_benchmark#61]
Hi, hoping that the coca model in https://github.com/mlfoundations/open_clip works and that https://github.com/mlfoundations/open_clip/pull/307 gets merged, I thought I might add some benchmarking for the generative part of the model on mscoco_captions, if it makes sense for this repository.

Before creating a PR I would also like to ask if adding https://github.com/sks3i/pycocoevalcap as a dependency is ok or not, it would make adding the benchmark simpler, otherwise I would add the metrics (bleu, cider, rouge and meteor) one by one.

**Comment by rom1504** [comment]
Yeah it's fine. Feel free to open a PR!
