### ISSUE TITLE
log dataset and model in new cli

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/CLIP_benchmark#76]
run.sh had that and it was nice to know progress

**Comment by djghosh13** [comment]
Do you mean just printing out model/dataset/progress percent after each one?

**Comment by djghosh13** [comment]
It looks like the dataset, model, and language (but not progress percent) are already printed out if you use `--verbose`

**Comment by rom1504** [comment]
opinion on removing verbose option and making it the default ?

**Comment by djghosh13** [comment]
I don't have a strong opinion one way or the other, but if we wanted to make that change, we could replace
```py
parser_eval.add_argument('--verbose', default=False, action="store_true", help="verbose mode")
```
with
```py
parser_eval.add_argument('--quiet', dest='verbose', action="store_false", help="suppress verbose messages")
```
to just flip the default verbosity (and also rename the cli option name correspondingly).

**Comment by rom1504** [comment]
yeah #78
