### ISSUE TITLE
bug in "build_dataset" function

### ISSUE THREAD

**Issue by JieyuZ2** [LAION-AI/CLIP_benchmark#85]
The following line will cause error when the task is "linear_probe", because the code only load `classnames, templates` when task is zeroshot, but the classnames would be used in the following line no matter what task it is....

https://github.com/LAION-AI/CLIP_benchmark/blob/c4d99276edfcc3c7559a92323cd3f7a374b22c06/clip_benchmark/datasets/builder.py#L92

**Comment by mehdidc** [comment]
Thanks @JieyuZ2 ! will fix this
