### ISSUE TITLE
Error when test on multilingual_mscoco

### ISSUE THREAD

**Issue by SingL3** [LAION-AI/CLIP_benchmark#87]
I think this line should be remove:
https://github.com/LAION-AI/CLIP_benchmark/blob/main/clip_benchmark/cli.py#L201

**Comment by 962858249** [comment]
> I think this line should be remove: https://github.com/LAION-AI/CLIP_benchmark/blob/main/clip_benchmark/cli.py#L201

I argee with you

**Comment by mehdidc** [comment]
multilingual_mscoco works fine for me, at least now, did this happen with WebDataset?

**Comment by SingL3** [comment]
@mehdidc I think it is fixed by #99. Formerly, L201 is now L203.
Closing this.
