### ISSUE TITLE
document how to run retrieval and generative eval using wds

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/CLIP_benchmark#91]
eg
https://github.com/LAION-AI/CLIP_benchmark#coco-captions-example
+
https://huggingface.co/datasets/clip-benchmark/wds_mscoco_captions2017/tree/main

**Comment by rom1504** [comment]
maybe something like `clip_benchmark eval --dataset=mscoco_captions --dataset_root="https://huggingface.co/datasets/clip-benchmark/wds_{dataset_cleaned}/tree/main" --task=mscoco_generative --model=coca_ViT-L-14 --output=result.json --batch_size=256 --pretrained=model.pt`

**Comment by mehdidc** [comment]
Yes the following work fine for retrieval:

`clip_benchmark eval --dataset=wds/mscoco_captions --dataset_root="https://huggingface.co/datasets/clip-benchmark/wds_{dataset_cleaned}/tree/main" --task=zeroshot_retrieval --model=ViT-B-32 --output=result.json`

for generative something similar with task `mscoco_generative`  does not seem to work, will fix it in a PR and add docs for both.

**Comment by mehdidc** [comment]
Done
