### ISSUE TITLE
Add babel imagenet 

### ISSUE THREAD

**Issue by rom1504** [LAION-AI/CLIP_benchmark#95]
https://github.com/gregor-ge/Babel-ImageNet

**Comment by mehdidc** [comment]
Done

**Comment by rom1504** [comment]
Adding usage instructions in the readme would be great

**Comment by mehdidc** [comment]
Ah right, will do, here one just needs to specify the language, e.g.

`clip_benchmark eval  --model xlm-roberta-base-ViT-B-32 --pretrained laion5b_s13b_b90k  --dataset babel_imagenet --dataset_root <ROOT> --language <LANG>`

**Comment by mehdidc** [comment]
Added here: https://github.com/LAION-AI/CLIP_benchmark#multilingual-evaluation
